Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import nibabel
from nilearn import plotting
import matplotlib
import numpy as np
import warnings
warnings.filterwarnings('ignore')

anat = nibabel.load('/data/ds000114/derivatives/fmriprep/sub-01/anat/sub-01_t1w_preproc.nii.gz')
fmri = nibabel.load('/data/ds000114/sub-01/ses-test/func/sub-01_ses-test_task-fingerfootlips_bold.nii.gz')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m/opt/conda/lib/python3.11/site-packages/nibabel/loadsave.py:101[0m, in [0;36mload[0;34m(filename, **kwargs)[0m
[1;32m    100[0m [38;5;28;01mtry[39;00m:
[0;32m--> 101[0m     stat_result [38;5;241m=[39m [43mos[49m[38;5;241;43m.[39;49m[43mstat[49m[43m([49m[43mfilename[49m[43m)[49m
[1;32m    102[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m:

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/data/ds000114/derivatives/fmriprep/sub-01/anat/sub-01_t1w_preproc.nii.gz'

During handling of the above exception, another exception occurred:

[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[1], line 8[0m
[1;32m      5[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mwarnings[39;00m
[1;32m      6[0m warnings[38;5;241m.[39mfilterwarnings([38;5;124m'[39m[38;5;124mignore[39m[38;5;124m'[39m)
[0;32m----> 8[0m anat [38;5;241m=[39m [43mnibabel[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m/data/ds000114/derivatives/fmriprep/sub-01/anat/sub-01_t1w_preproc.nii.gz[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      9[0m fmri [38;5;241m=[39m nibabel[38;5;241m.[39mload([38;5;124m'[39m[38;5;124m/data/ds000114/sub-01/ses-test/func/sub-01_ses-test_task-fingerfootlips_bold.nii.gz[39m[38;5;124m'[39m)

File [0;32m/opt/conda/lib/python3.11/site-packages/nibabel/loadsave.py:103[0m, in [0;36mload[0;34m(filename, **kwargs)[0m
[1;32m    101[0m     stat_result [38;5;241m=[39m os[38;5;241m.[39mstat(filename)
[1;32m    102[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m:
[0;32m--> 103[0m     [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNo such file or no access: [39m[38;5;124m'[39m[38;5;132;01m{[39;00mfilename[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m"[39m)
[1;32m    104[0m [38;5;28;01mif[39;00m stat_result[38;5;241m.[39mst_size [38;5;241m<[39m[38;5;241m=[39m [38;5;241m0[39m:
[1;32m    105[0m     [38;5;28;01mraise[39;00m ImageFileError([38;5;124mf[39m[38;5;124m"[39m[38;5;124mEmpty file: [39m[38;5;124m'[39m[38;5;132;01m{[39;00mfilename[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m"[39m)

[0;31mFileNotFoundError[0m: No such file or no access: '/data/ds000114/derivatives/fmriprep/sub-01/anat/sub-01_t1w_preproc.nii.gz'

